np.where的测试

In [1]:
import numpy as np
x = np.array([[0, 0, 1], 
    [0, 1, 1], 
    [1, 0, 0]])

In [2]:
y = np.where(x == 1)

In [3]:
x

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 0]])

In [5]:
x.mean(axis = 0)

array([0.33333333, 0.33333333, 0.66666667])

In [11]:
y[1]

array([2, 1, 2, 0])

In [17]:
z = np.array([1, 1, 3])
w = 1
y = np.where(z == w)

In [18]:
y

(array([0, 1]),)

In [19]:
np.ones([2, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.savetxt('/home/lhospital/MyProgramm/CR_based_HSI/expResult/pJCR/test.cvs', x, delimiter = ',')